\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Homework 1},
            pdfauthor={jiaying Ning},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Homework 1}
\author{jiaying Ning}
\date{9/23/2020}

\begin{document}
\maketitle

\textbf{Problem 1}

load packages

import data

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Using the entire sample, provide descriptive statistics for all
  variables of interest.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Total sample size for each variable (N); Mean/SD, Median/IQR, Min and
  Max for continuous variables; Frequency/Percentages for categorical
  variables; Number of missing values for each variable. (8p)
\item
  Generate a his togram for the Ig-M values and comment on its shape.
  (2p)
\end{enumerate}

since the only continuous variable is Antibody\_Igm. We will be taking
the descriptive statistics measure for this continuous variable.

below are its overall summary and desctiptive value table

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#overall summary}
\KeywordTok{summary}\NormalTok{(Antibodies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Subject       AgeCategory  Antibody_IgM                  Smell     
##  Min.   :   1.0   18-30:318   Min.   :0.0480   Altered          :1047  
##  1st Qu.: 632.5   31-50:810   1st Qu.:0.0690   Normal           : 410  
##  Median :1373.0   51+  :363   Median :0.0915   Unanswered/Others:  34  
##  Mean   :1413.8               Mean   :0.1239                           
##  3rd Qu.:2190.5               3rd Qu.:0.1290                           
##  Max.   :2917.0               Max.   :1.0475                           
##                               NA's   :1224                             
##     Gender   
##  Female:981  
##  Male  :510  
##              
##              
##              
##              
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#print out the class table for each variable in the dataset}
\KeywordTok{t}\NormalTok{(}\KeywordTok{t}\NormalTok{(}\KeywordTok{sapply}\NormalTok{(Antibodies, class)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              [,1]     
## Subject      "integer"
## AgeCategory  "factor" 
## Antibody_IgM "numeric"
## Smell        "factor" 
## Gender       "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#print out the descriptive statistics}
\NormalTok{descriptivestats =}\StringTok{ }\KeywordTok{summary}\NormalTok{(}\KeywordTok{na.omit}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Antibody_IgM))}
\NormalTok{descriptivestats}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0480  0.0690  0.0915  0.1239  0.1290  1.0475
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{IQR}\NormalTok{(}\KeywordTok{na.omit}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Antibody_IgM))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.06
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(}\KeywordTok{na.omit}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Antibody_IgM))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1104458
\end{verbatim}

From the dataset, I observe that only meaningful variable that is
numeric is ``Antibody\_IgM''. Variable
``AgeCategory'',``Smell'',``Gender'' are all factor.

For continuous variable: Antibody\_Igm has means of 0.1238839 with
standard deviation of 0.1104458, median of 0.0915 and IQR of 0.06.Its
min is 0.048 and max is 1.0475

For categorical variable the frequency and proportion of agegroup is:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#frequency for categorical variable}
\CommentTok{##frequency of age category}
\KeywordTok{table}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{AgeCategory)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 18-30 31-50   51+ 
##   318   810   363
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{AgeCategory))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##     18-30     31-50       51+ 
## 0.2132797 0.5432596 0.2434608
\end{verbatim}

the frequency and proportion of subject's smell status is:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{##frequency of smell}
\KeywordTok{table}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Smell)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##           Altered            Normal Unanswered/Others 
##              1047               410                34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Smell))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##           Altered            Normal Unanswered/Others 
##        0.70221328        0.27498323        0.02280349
\end{verbatim}

the frequency and proportion of smell is:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{##frequency of Gender}
\KeywordTok{table}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Gender)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Female   Male 
##    981    510
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(Antibodies}\OperatorTok{$}\NormalTok{Gender))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    Female      Male 
## 0.6579477 0.3420523
\end{verbatim}

From the summary table we know that there are 1224 NA values in
Antibody\_Igm variable. 34 unanswered/other in smell category.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{Antibodies,}\DataTypeTok{mapping=}\KeywordTok{aes}\NormalTok{((Antibody_IgM))) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1224 rows containing non-finite values (stat_bin).
\end{verbatim}

\includegraphics{Homework1_jn2761_files/figure-latex/histogram IGM-1.pdf}
From the graph showing above, we can see that the distribution is
skewing to the right. Most people have low antibody\_igm.

\textbf{problem 2}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Provide descriptive statistics for all variables, stratified by smell
  category.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Provide descriptive statistics for all the other variables by the two
  smell categories (normal vs altered) and present them in a tabular
  form (see example below). Briefly comment on the differences observed
  between the two groups. (6p) Hint: tableby() in R can easily generate
  this, but feel free to create your own table in Word.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}
\KeywordTok{library}\NormalTok{(furniture)}

\KeywordTok{table1}\NormalTok{(Antibodies,AgeCategory,Subject,Antibody_IgM,Gender,}\DataTypeTok{splitby =} \StringTok{"Smell"}\NormalTok{,   }\DataTypeTok{row_wise =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ────────────────────────────────────────────────────────────
##                                 Smell 
##               Altered       Normal        Unanswered/Others
##               n = 178       n = 81        n = 8            
##  AgeCategory                                               
##     18-30     36 (67.9%)    13 (24.5%)    4 (7.5%)         
##     31-50     101 (68.2%)   43 (29.1%)    4 (2.7%)         
##     51+       41 (62.1%)    25 (37.9%)    0 (0%)           
##  Subject                                                   
##               585.9 (517.6) 622.9 (671.0) 722.4 (622.8)    
##  Antibody_IgM                                              
##               0.1 (0.1)     0.1 (0.1)     0.1 (0.1)        
##  Gender                                                    
##     Female    120 (69%)     47 (27%)      7 (4%)           
##     Male      58 (62.4%)    34 (36.6%)    1 (1.1%)         
## ────────────────────────────────────────────────────────────
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Antibodies_clear =}\StringTok{ }\KeywordTok{filter}\NormalTok{(Antibodies, Smell }\OperatorTok{!=}\StringTok{ "Unanswered/Others"}\NormalTok{)}
\KeywordTok{table1}\NormalTok{(Antibodies_clear,AgeCategory,Subject,Antibody_IgM,Gender,}\DataTypeTok{splitby =} \StringTok{"Smell"}\NormalTok{,   }\DataTypeTok{row_wise =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ──────────────────────────────────────────
##                        Smell 
##               Altered       Normal       
##               n = 178       n = 81       
##  AgeCategory                             
##     18-30     36 (73.5%)    13 (26.5%)   
##     31-50     101 (70.1%)   43 (29.9%)   
##     51+       41 (62.1%)    25 (37.9%)   
##  Subject                                 
##               585.9 (517.6) 622.9 (671.0)
##  Antibody_IgM                            
##               0.1 (0.1)     0.1 (0.1)    
##  Gender                                  
##     Female    120 (71.9%)   47 (28.1%)   
##     Male      58 (63%)      34 (37%)     
## ──────────────────────────────────────────
\end{verbatim}

Overall, more people reported having their smell altered than not. This
difference in proportion is true among all age group and gender.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Use the Ig-M variable to generate side-by-side histograms and boxplots
  by smell categories
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Antibodies_clear,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Antibody_IgM,}\DataTypeTok{fill=}\NormalTok{Smell))}\OperatorTok{+}\KeywordTok{geom_histogram}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1198 rows containing non-finite values (stat_bin).
\end{verbatim}

\includegraphics{Homework1_jn2761_files/figure-latex/side by side histogram and boxplot-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Antibodies_clear, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Smell, }\DataTypeTok{y=}\NormalTok{Antibody_IgM, }\DataTypeTok{fill=}\NormalTok{Smell)) }\OperatorTok{+}\StringTok{ }
\StringTok{    }\KeywordTok{geom_boxplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1198 rows containing non-finite values (stat_boxplot).
\end{verbatim}

\includegraphics{Homework1_jn2761_files/figure-latex/side by side histogram and boxplot-2.pdf}

(normal vs altered). Make sure you label your figures appropriately and
briefly discuss the trends observed. (4p)

Btoh histogram skewed to the right, with most participants having
relatively lower IGM value. However, the variation for altered-smell
participants seems to be larger than normal participants. The average of
IGM is also higher than altered-smell group. Further more, the
altered-smell group seem to have more extremed IGM value than normal
group.

\#\#problem 2

In this article, author discussed a study done by Professor Shoveller
who suggested that cats that eats only one meals a day might feel more
satisfied and have healthier body than cats who eats several small meals
a day. To present this fact, the author compares this result to another
more widely accepted theory, which is that ``eating small meals several
days is better for cats''. Then the author shortly explained how the
study set up and lay out the conclusion of the study.

Summary: The main goal of the study is to examine how feeding frequency
impact cats' mental and physical state. Total of 8 cats with similar age
are included in the study, all cats are assigned with the same food. The
study used a 2X3 replicated incomplete Latin square design. The study
does not specify whether cats are randomly assigned to treatment. Some
potential bias might include: 1. Even though precise measurement for
health and behavior is recorded for each cat, the sample size might
still be too small to be generalized to a larger cat population 2.
Different feeder prepares different type of food for their cat, and the
quality of food can have strong impact on a cats' mental and physical
state. Therefore, since all cats are assigned with the same canned food
in the study, it is not clear whether the food choice can be a potential
confounding variable.

Journal/Newspaper Reference: Leggate, J. (2020, September 24). You might
be feeding your cats wrong, according to a new study. Fox News.
\url{https://www.foxnews.com/lifestyle/feeding-cats-wrong-new-study}
Original Study reference: Camara A, Verbrugghe A, Cargo-Froom C, Hogan
K, DeVries TJ, et al. (2020) The daytime feeding frequency affects
appetite-regulating hormones, amino acids, physical activity, and
respiratory quotient, but not energy expenditure, in adult cats fed
regimens for 21 days. PLOS ONE 15(9): e0238522.

\end{document}
